# Generated by Django 4.2.23 on 2025-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_name_order_products_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kkal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('inactive', 'Не активен'), ('canceled', 'Отменен')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sweets', 'Сладости'), ('drinks', 'Напитки'), ('bakery', 'Хлебобулочные изделия'), ('snacks', 'Снеки'), ('meat', 'Мясо, яйца, рыба'), ('dairy', 'Молочные продукты'), ('other', 'Другое')], max_length=50),
        ),
    ]
