# Generated by Django 4.2.23 on 2025-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash',
            field=models.BooleanField(default=False),
        ),
    ]
