# Generated by Django 4.2.23 on 2025-06-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sweets', 'Сладости'), ('drinks', 'Напитки'), ('bakery', 'Хлебобулочные изделия'), ('snacks', 'Снеки'), ('meat', 'Мясо, яйца, рыба'), ('dairy', 'Молочные продукты'), ('fruit', 'Фрукты'), ('vegetables', 'Овощи'), ('sauces', 'Соусы'), ('spices', 'Специи'), ('other', 'Другое')], max_length=50),
        ),
    ]
