# Generated by Django 4.2.23 on 2025-07-06 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_product_weight_product_weight_dependence'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='phone_number',
            field=models.CharField(default='+79999999999', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='StoryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contnent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
