# Generated by Django 4.2.23 on 2025-07-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_courier_phone_number_storyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buying_mostly',
            field=models.BooleanField(default=False),
        ),
    ]
