# Generated by Django 4.2.23 on 2025-07-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_buying_mostly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buying_mostly',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sweets', 'Сладости'), ('drinks', 'Напитки'), ('bakery', 'Хлебобулочные изделия'), ('snacks', 'Снеки'), ('meat', 'Мясо, яйца, рыба'), ('dairy', 'Молочные продукты'), ('fruit', 'Фрукты'), ('vegetables', 'Овощи'), ('sauces', 'Соусы'), ('spices', 'Специи'), ('other', 'Другое'), ('buying_leaders', 'Покупают чаще всего'), ('new', 'Новинки')], max_length=50),
        ),
    ]
