# Generated by Django 4.2.23 on 2025-07-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_category_parent_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='children', to='store.category'),
        ),
    ]
