# Generated by Django 4.2.23 on 2025-07-27 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0018_remove_category_parent_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('max_usage_count', models.PositiveIntegerField(blank=True, null=True)),
                ('min_order_price', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_percent', models.PositiveIntegerField()),
                ('discount_type', models.CharField(choices=[('delivery', 'Скидка на доставку'), ('cart', 'Скидка на всю корзину'), ('item', 'Скидка на конкретный товар'), ('category', 'Скидка на категорию')], default='cart', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserPromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'promo_code')},
            },
        ),
    ]
