# Generated by Django 4.2.23 on 2025-07-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_promocode_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='expires_at',
        ),
    ]
