# Generated by Django 4.2.23 on 2025-07-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_promocode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
