# Generated by Django 4.2.23 on 2025-07-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_promocode_usage_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='usage_count',
        ),
        migrations.AddField(
            model_name='userpromocodeusage',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
