# Generated by Django 4.2.23 on 2025-07-28 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_promocode_usage_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportreport',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userpromocodeusage',
            name='active_usage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpromocodeusage',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='store.promocode'),
        ),
    ]
