# Generated by Django 4.2.23 on 2025-07-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_supportreport_email_userpromocodeusage_active_usage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_amount',
            new_name='discount_price',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
