# Generated by Django 4.2.23 on 2025-08-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_order_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='to_door',
            field=models.BooleanField(default=False),
        ),
    ]
