# Generated by Django 4.2.23 on 2025-08-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='edits',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
