# Generated by Django 4.2.23 on 2025-08-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_order_edits_order_corrections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='corrections',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
