# Generated by Django 6.0.1 on 2026-01-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_loginattempt_order_change_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/images/default.png', upload_to='products/'),
        ),
    ]
