# Generated by Django 4.2.23 on 2025-06-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_profile_adress_profile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='active_deliveries',
            field=models.BooleanField(default=False),
        ),
    ]
