# Generated by Django 4.2.23 on 2025-07-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_profile_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='promocode_activated',
            field=models.BooleanField(default=False),
        ),
    ]
