# Generated by Django 4.2.23 on 2025-07-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_profile_promocode_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='promocode_activated',
        ),
    ]
