# Generated by Django 4.2.23 on 2025-08-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_emailverificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_deliveries',
        ),
    ]
