# Generated by Django 4.2.23 on 2025-08-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_remove_profile_active_deliveries'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_deliveries',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
